// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StaticLatency struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticLatency) Reset()         { *m = StaticLatency{} }
func (m *StaticLatency) String() string { return proto.CompactTextString(m) }
func (*StaticLatency) ProtoMessage()    {}
func (*StaticLatency) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *StaticLatency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticLatency.Unmarshal(m, b)
}
func (m *StaticLatency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticLatency.Marshal(b, m, deterministic)
}
func (m *StaticLatency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticLatency.Merge(m, src)
}
func (m *StaticLatency) XXX_Size() int {
	return xxx_messageInfo_StaticLatency.Size(m)
}
func (m *StaticLatency) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticLatency.DiscardUnknown(m)
}

var xxx_messageInfo_StaticLatency proto.InternalMessageInfo

func (m *StaticLatency) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type NormalLatency struct {
	Mean                 int32    `protobuf:"varint,1,opt,name=mean,proto3" json:"mean,omitempty"`
	Stddev               int32    `protobuf:"varint,2,opt,name=stddev,proto3" json:"stddev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NormalLatency) Reset()         { *m = NormalLatency{} }
func (m *NormalLatency) String() string { return proto.CompactTextString(m) }
func (*NormalLatency) ProtoMessage()    {}
func (*NormalLatency) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *NormalLatency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalLatency.Unmarshal(m, b)
}
func (m *NormalLatency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalLatency.Marshal(b, m, deterministic)
}
func (m *NormalLatency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalLatency.Merge(m, src)
}
func (m *NormalLatency) XXX_Size() int {
	return xxx_messageInfo_NormalLatency.Size(m)
}
func (m *NormalLatency) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalLatency.DiscardUnknown(m)
}

var xxx_messageInfo_NormalLatency proto.InternalMessageInfo

func (m *NormalLatency) GetMean() int32 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *NormalLatency) GetStddev() int32 {
	if m != nil {
		return m.Stddev
	}
	return 0
}

type Latency struct {
	// Types that are valid to be assigned to LatencyType:
	//	*Latency_Static
	//	*Latency_Normal
	LatencyType          isLatency_LatencyType `protobuf_oneof:"latency_type"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Latency) Reset()         { *m = Latency{} }
func (m *Latency) String() string { return proto.CompactTextString(m) }
func (*Latency) ProtoMessage()    {}
func (*Latency) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *Latency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Latency.Unmarshal(m, b)
}
func (m *Latency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Latency.Marshal(b, m, deterministic)
}
func (m *Latency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Latency.Merge(m, src)
}
func (m *Latency) XXX_Size() int {
	return xxx_messageInfo_Latency.Size(m)
}
func (m *Latency) XXX_DiscardUnknown() {
	xxx_messageInfo_Latency.DiscardUnknown(m)
}

var xxx_messageInfo_Latency proto.InternalMessageInfo

type isLatency_LatencyType interface {
	isLatency_LatencyType()
}

type Latency_Static struct {
	Static *StaticLatency `protobuf:"bytes,1,opt,name=static,proto3,oneof"`
}

type Latency_Normal struct {
	Normal *NormalLatency `protobuf:"bytes,2,opt,name=normal,proto3,oneof"`
}

func (*Latency_Static) isLatency_LatencyType() {}

func (*Latency_Normal) isLatency_LatencyType() {}

func (m *Latency) GetLatencyType() isLatency_LatencyType {
	if m != nil {
		return m.LatencyType
	}
	return nil
}

func (m *Latency) GetStatic() *StaticLatency {
	if x, ok := m.GetLatencyType().(*Latency_Static); ok {
		return x.Static
	}
	return nil
}

func (m *Latency) GetNormal() *NormalLatency {
	if x, ok := m.GetLatencyType().(*Latency_Normal); ok {
		return x.Normal
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Latency) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Latency_OneofMarshaler, _Latency_OneofUnmarshaler, _Latency_OneofSizer, []interface{}{
		(*Latency_Static)(nil),
		(*Latency_Normal)(nil),
	}
}

func _Latency_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Latency)
	// latency_type
	switch x := m.LatencyType.(type) {
	case *Latency_Static:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Static); err != nil {
			return err
		}
	case *Latency_Normal:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Normal); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Latency.LatencyType has unexpected type %T", x)
	}
	return nil
}

func _Latency_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Latency)
	switch tag {
	case 1: // latency_type.static
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StaticLatency)
		err := b.DecodeMessage(msg)
		m.LatencyType = &Latency_Static{msg}
		return true, err
	case 2: // latency_type.normal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NormalLatency)
		err := b.DecodeMessage(msg)
		m.LatencyType = &Latency_Normal{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Latency_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Latency)
	// latency_type
	switch x := m.LatencyType.(type) {
	case *Latency_Static:
		s := proto.Size(x.Static)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Latency_Normal:
		s := proto.Size(x.Normal)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*StaticLatency)(nil), "client.StaticLatency")
	proto.RegisterType((*NormalLatency)(nil), "client.NormalLatency")
	proto.RegisterType((*Latency)(nil), "client.Latency")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x54, 0xb9, 0x78,
	0x83, 0x4b, 0x12, 0x4b, 0x32, 0x93, 0x7d, 0x12, 0x4b, 0x52, 0xf3, 0x92, 0x2b, 0x85, 0x44, 0xb8,
	0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x25,
	0x6b, 0x2e, 0x5e, 0xbf, 0xfc, 0xa2, 0xdc, 0xc4, 0x1c, 0x98, 0x32, 0x21, 0x2e, 0x96, 0xdc, 0xd4,
	0xc4, 0x3c, 0xa8, 0x2a, 0x30, 0x5b, 0x48, 0x8c, 0x8b, 0xad, 0xb8, 0x24, 0x25, 0x25, 0xb5, 0x4c,
	0x82, 0x09, 0x2c, 0x0a, 0xe5, 0x29, 0x55, 0x73, 0xb1, 0xc3, 0xb4, 0xe9, 0x83, 0x94, 0x80, 0xac,
	0x03, 0x6b, 0xe4, 0x36, 0x12, 0xd5, 0x83, 0xba, 0x0a, 0xc5, 0x11, 0x1e, 0x0c, 0x41, 0x50, 0x65,
	0x20, 0x0d, 0x79, 0x60, 0x8b, 0xc1, 0x66, 0x22, 0x69, 0x40, 0x71, 0x0e, 0x48, 0x03, 0x44, 0x99,
	0x13, 0x1f, 0x17, 0x4f, 0x0e, 0x44, 0x30, 0xbe, 0xa4, 0xb2, 0x20, 0x35, 0x89, 0x0d, 0xec, 0x5f,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xcf, 0x8e, 0x73, 0xff, 0x00, 0x00, 0x00,
}
